#!/usr/bin/env python3
"""Re-download the site's web fonts into fonts/, self-hosted.

    python3 tools/vendor_fonts.py

The site used to pull Barlow Condensed and Inter straight from
fonts.googleapis.com. That is one third-party runtime dependency on the first
paint of every page, and it is simply absent in the packaged desktop build,
which has no network at all. This writes fonts/fonts.css plus the .woff2 files
it points at, and index.html links that instead.

Two things this does that a naive download does not:

* ONLY the `latin` and `latin-ext` subsets. Google serves seven (cyrillic,
  greek, vietnamese, ...). The UI is English and Finnish; the other five are
  roughly twice the bytes for glyphs nothing renders.
* DEDUPES by content. Inter is a VARIABLE font, so Google hands back the exact
  same 48 KB file for weight 400, 500, 600 and 700 — four @font-face blocks,
  one file. Keying the filename on the bytes instead of the weight turns 530 KB
  of downloads into 265 KB on disk, with all four blocks pointing at one file.

Licence: both families are SIL Open Font License 1.1.
"""
import hashlib
import pathlib
import re
import subprocess
import sys

CSS_URL = ("https://fonts.googleapis.com/css2"
           "?family=Barlow+Condensed:wght@500;600;700"
           "&family=Inter:wght@400;500;600;700&display=swap")
# Google serves woff2 only to a browser UA; curl's default gets ttf.
UA = ("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0 Safari/537.36")
KEEP = {"latin", "latin-ext"}

HERE = pathlib.Path(__file__).resolve().parent.parent
OUT = HERE / "fonts"

HEADER = """/* Barlow Condensed + Inter, self-hosted.
   Generated by tools/vendor_fonts.py — do not hand-edit.

   These live in the repo so the site has no third-party runtime dependency and
   the packaged desktop build renders identically with no network. Only the
   `latin` and `latin-ext` subsets are here: the UI is English and Finnish, and
   the other five subsets Google serves are ~2x the bytes for glyphs nothing
   uses. Inter is a variable font, so its four weights all point at one file.

   Both families are SIL Open Font License 1.1. */
"""


def fetch(url, ua=False):
    cmd = ["curl", "-fsSL", url]
    if ua:
        cmd[2:2] = ["-A", UA]
    return subprocess.run(cmd, capture_output=True, check=True).stdout


def main():
    css = fetch(CSS_URL, ua=True).decode("utf-8")
    # every block is introduced by a "/* subset */" comment
    parts = re.split(r"/\*\s*([a-z0-9-]+)\s*\*/", css)
    OUT.mkdir(exist_ok=True)
    blocks, by_hash, written = [], {}, 0
    for i in range(1, len(parts), 2):
        subset, block = parts[i], parts[i + 1]
        if subset not in KEEP:
            continue
        url = re.search(r"url\((https://[^)]+\.woff2)\)", block).group(1)
        fam = re.search(r"font-family:\s*'([^']+)'", block).group(1)
        data = fetch(url)
        digest = hashlib.sha256(data).hexdigest()[:8]
        name = by_hash.get(digest)
        if name is None:
            name = "%s-%s-%s.woff2" % (fam.replace(" ", ""), subset, digest)
            (OUT / name).write_bytes(data)
            by_hash[digest] = name
            written += 1
        blocks.append("/* %s */\n%s" % (subset, block.replace(url, name).strip()))

    (OUT / "fonts.css").write_text(HEADER + "\n" + "\n\n".join(blocks) + "\n",
                                   encoding="utf-8")
    # Anything left from an older run would be dead weight in the AppImage.
    stale = [p for p in OUT.glob("*.woff2") if p.name not in by_hash.values()]
    for p in stale:
        p.unlink()
    print("fonts/: %d faces -> %d files (%d stale removed)"
          % (len(blocks), written, len(stale)))


if __name__ == "__main__":
    sys.exit(main())
